
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ComentariosProducto
{

    public int idProductoComentario { get; set; }

    public int comentarioId { get; set; }

    public int productoId { get; set; }

    public string comentario { get; set; }

    public int estrellas { get; set; }

    public bool visible { get; set; }



    public virtual Comentarios Comentarios { get; set; }

    public virtual Productos Productos { get; set; }

}

}
