
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comentarios
{

    public Comentarios()
    {

        this.ComentariosProducto = new HashSet<ComentariosProducto>();

    }


    public int idComentario { get; set; }

    public System.DateTime fecha { get; set; }

    public int vecinoId { get; set; }

    public int compraId { get; set; }



    public virtual Compras Compras { get; set; }

    public virtual Vecinos Vecinos { get; set; }

    public virtual ICollection<ComentariosProducto> ComentariosProducto { get; set; }

}

}
