
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Compras
{

    public Compras()
    {

        this.ComentariosProducto = new HashSet<ComentariosProducto>();

        this.CompraProducto = new HashSet<CompraProducto>();

    }


    public int idCompra { get; set; }

    public System.DateTime fecha { get; set; }

    public int vecinoId { get; set; }

    public int tandaId { get; set; }

    public int localId { get; set; }

    public int estadoId { get; set; }



    public virtual ICollection<ComentariosProducto> ComentariosProducto { get; set; }

    public virtual ICollection<CompraProducto> CompraProducto { get; set; }

    public virtual EstadosCompra EstadosCompra { get; set; }

    public virtual Locales Locales { get; set; }

    public virtual Tandas Tandas { get; set; }

    public virtual Vecinos Vecinos { get; set; }

}

}
