
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CompraProducto
{

    public int idCompraProducto { get; set; }

    public int compraId { get; set; }

    public int productoId { get; set; }

    public int cantidad { get; set; }



    public virtual Compras Compras { get; set; }

    public virtual Productos Productos { get; set; }

}

}
