
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EstadosCompra
{

    public EstadosCompra()
    {

        this.Compras = new HashSet<Compras>();

    }


    public int idEstadoCompra { get; set; }

    public string nombre { get; set; }

    public int codigo { get; set; }



    public virtual ICollection<Compras> Compras { get; set; }

}

}
