
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Locales
{

    public Locales()
    {

        this.Compras = new HashSet<Compras>();

        this.Vecinos = new HashSet<Vecinos>();

    }


    public int idLocal { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string barrio { get; set; }

    public string horario { get; set; }

    public int comuna { get; set; }

    public int circuitoId { get; set; }

    public bool activo { get; set; }



    public virtual Circuitos Circuitos { get; set; }

    public virtual ICollection<Compras> Compras { get; set; }

    public virtual ICollection<Vecinos> Vecinos { get; set; }

}

}
