
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Precios
{

    public int idPrecio { get; set; }

    public decimal precio { get; set; }

    public System.DateTime fecha { get; set; }

    public Nullable<int> productoId { get; set; }



    public virtual Productos Productos { get; set; }

}

}
