
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Productos
{

    public Productos()
    {

        this.ComentariosProducto = new HashSet<ComentariosProducto>();

        this.CompraProducto = new HashSet<CompraProducto>();

        this.Costos = new HashSet<Costos>();

        this.Precios = new HashSet<Precios>();

    }


    public int idProducto { get; set; }

    public string producto { get; set; }

    public string descripcion { get; set; }

    public string marca { get; set; }

    public string presentacion { get; set; }

    public int stock { get; set; }

    public bool activo { get; set; }

    public Nullable<int> categoriaId { get; set; }



    public virtual Categorias Categorias { get; set; }

    public virtual ICollection<ComentariosProducto> ComentariosProducto { get; set; }

    public virtual ICollection<CompraProducto> CompraProducto { get; set; }

    public virtual ICollection<Costos> Costos { get; set; }

    public virtual ICollection<Precios> Precios { get; set; }

}

}
