
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Relevamientos
{

    public int idRelevamiento { get; set; }

    public string fruta { get; set; }

    public string tipo { get; set; }

    public int cantidad { get; set; }

    public decimal precio { get; set; }

    public string donde { get; set; }

    public System.DateTime fechaRelevado { get; set; }

    public System.DateTime fechaSincronizado { get; set; }

}

}
