
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tandas
{

    public Tandas()
    {

        this.Compras = new HashSet<Compras>();

    }


    public int idTanda { get; set; }

    public System.DateTime fechaAbierto { get; set; }

    public Nullable<System.DateTime> fechaCerrado { get; set; }

    public int circuitoId { get; set; }

    public int vecinoId { get; set; }



    public virtual Circuitos Circuitos { get; set; }

    public virtual ICollection<Compras> Compras { get; set; }

    public virtual Vecinos Vecinos { get; set; }

}

}
