
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Vecinos
{

    public Vecinos()
    {

        this.Comentarios = new HashSet<Comentarios>();

        this.Compras = new HashSet<Compras>();

        this.RolesVecinos = new HashSet<RolesVecinos>();

        this.Tandas = new HashSet<Tandas>();

    }


    public int idVecino { get; set; }

    public string correo { get; set; }

    public string nombres { get; set; }

    public string telefono { get; set; }

    public Nullable<int> comuna { get; set; }

    public string contrasena { get; set; }

    public string hash { get; set; }

    public bool verificado { get; set; }

    public Nullable<int> localId { get; set; }



    public virtual ICollection<Comentarios> Comentarios { get; set; }

    public virtual ICollection<Compras> Compras { get; set; }

    public virtual Locales Locales { get; set; }

    public virtual ICollection<RolesVecinos> RolesVecinos { get; set; }

    public virtual ICollection<Tandas> Tandas { get; set; }

}

}
